const {
  GREENLIGHT_API_ENDPOINT,
  GREENLIGHT_API_TOKEN,
  MAILCHIMP_API_KEY,
  MAILCHIMP_AUDIENCE_ID,
  SIGNUP_API_ENDPOINT = '',
} = process.env;

export const config = {
  GREENLIGHT_API_ENDPOINT,
  GREENLIGHT_API_TOKEN,
  MAILCHIMP_API_KEY,
  MAILCHIMP_AUDIENCE_ID,
  SIGNUP_API_ENDPOINT,
};
