export const GOOGLE_ANALYTICS_ID = process.env.GOOGLE_ANALYTICS_ID;
export const OVERRIDE_NODE_ENV = process.env.OVERRIDE_NODE_ENV;
export const FB_PIXEL_ID = process.env.FB_PIXEL_ID;
export const HIGHSCHOOL_FORM_ACTIVE_UNTIL = process.env.HIGHSCHOOL_FORM_ACTIVE_UNTIL;
export const HIGHSCHOOL_FORM_RESPONSES_NAME = process.env.HIGHSCHOOL_FORM_RESPONSES_NAME;
export const SENTRY_ENVIRONMENT = process.env.SENTRY_ENVIRONMENT;
export const SIGNUP_API_ENDPOINT = process.env.SIGNUP_API_ENDPOINT;

const clientEnvironmentVariables = {
  GOOGLE_ANALYTICS_ID,
  OVERRIDE_NODE_ENV,
  FB_PIXEL_ID,
  HIGHSCHOOL_FORM_ACTIVE_UNTIL,
  HIGHSCHOOL_FORM_RESPONSES_NAME,
  SENTRY_ENVIRONMENT,
  SIGNUP_API_ENDPOINT,
};

export default clientEnvironmentVariables;
