name: Unit Tests
on: [push]
jobs:
  jest-tests:
    name: Run Jest Tests
    runs-on: ubuntu-latest
    environment: test
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install Dependencies
        uses: actions/setup-node@v3
        with:
          node-version: '22'
      - run: npm install
      - run: npm test
